# Generated by Django 5.0.2 on 2024-08-14 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='images_imag_created_d57897_idx',
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='images_imag_created_6393be_idx'),
        ),
    ]
